### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Mr-BrockLee** [Fan7asy/Client#5]
Is there a way you can draw virus like 
```JS   // Very simple leaderboard
    for (var i = 0; i < leaderboard.length; i++) {
        const section = leaderboard[i];
        const name = (i + 1) + ". " + section.name;
        ctx.globalAlpha = .8;
        ctx.strokeStyle = "#000"
        ctx.font = '15px Tahoma';
        ctx.fillStyle = "#FFF";
        ctx.fillText(name, (ctx.canvas.width - 200), 40 + 24 * i);
    };
```
See the leaderboard is almost fully customizable  Is there a way u can make to so we can customize color/opacity etc, bcz I am trying to make it work with color picker for user pref
Color is changeable through server side but it wont allow users to choose what they want.

**Comment by Fan7asy** [comment]
You asked a virus question and presented leaderboard code.

**Comment by Fan7asy** [comment]
Can you explain what the issue is, because I do not understand.

**Comment by Mr-BrockLee** [comment]
Is there a way u can make virus more customizable just like the leaderboard is?

**Comment by Fan7asy** [comment]
Yeah you can apply some of the attributes like `globalAlpha`, etc.

**Comment by Mr-BrockLee** [comment]
im trash at js can u make it so we can do tha?

**Comment by alktbihd** [comment]
its basic canvas

**Comment by Mr-BrockLee** [comment]
@alktbihd can u do it for me?
since `its basic canvas`

**Comment by Fan7asy** [comment]
So, in order to customise the Virus you will need to first put it into focus with an `if` statement.
You will need to place the following snippet inside the `drawOneCell` function that starts at around line [867](https://github.com/Fan7asy/Client/blob/master/js/main.js#L867l).

```JS
if (this.isVirus) {
             
};
```

Next you may add your attributes, for example:

```JS
if (this.isVirus) {
     ctx.globalAlpha = .7;  
};
```

`ctx.globalAlpha` refers to the opacity of the object currently in focus (In this case the virus);
You may adjust this to your liking by increasing and decreasing the value.

You may also want to read up on how to use canvas at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D)
